# Netlify configuration for Next.js app
[build]
  command = "yarn build:app"
  publish = "packages/app/.next"

[dev]
  command = "yarn dev:app"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/api/script.js"
  to = "https://app.rybbit.io/api/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/track"
  to = "https://app.rybbit.io/api/track"
  status = 200
  force = true

# Optional: Disable x-powered-by header and source maps in production handled by Next.js config
# No direct mapping needed in netlify.toml
