[build]
  command = "yarn build:app"
  publish = "packages/app/.next"

[build.environment]
  NODE_VERSION = "22.14.0"
  YARN_VERSION = "4.9.2"

[[redirects]]
  from = "/api/script.js"
  to = "https://app.rybbit.io/api/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/track"
  to = "https://app.rybbit.io/api/track"
  status = 200
  force = true
