[build]
  command = "yarn build:web"
  publish = "packages/web/.next"

[build.environment]
  NODE_VERSION = "22.14.0"
  YARN_VERSION = "4.9.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[[redirects]]
  from = "/api/script.js"
  to = "https://opensky.folktizen.xyz/api/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/track"
  to = "https://opensky.folktizen.xyz/api/track"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Server = "Unix"
    X-Powered-By = "PHP/7.4.0"
    X-Turbo-Charged-By = "LiteSpeed"
