[profile.default]
src = 'src'
test = 'tests'
libs = ['lib']
out = 'out'
optimizer = true
solc_version = '0.8.20'
evm_version = 'london'

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
optimism = "${OPTIMISTIC_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"
linea = "${LINEA_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY_V2}" }
optimism = { key = "${ETHERSCAN_API_KEY_V2}" }
polygon = { key = "${ETHERSCAN_API_KEY_V2}" }
base = { key = "${ETHERSCAN_API_KEY_V2}" }
linea = { key = "${ETHERSCAN_API_KEY_V2}" }

[fmt]
tab_width = 2
line_length = 120
bracket_spacing = true
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
ignore = ["lib/**"]
