[profile.default]
src = 'src'
test = 'tests'
libs = ['lib']
out = 'out'
optimizer = true
solc_version = '0.8.20'
evm_version = 'london'

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }

[fmt]
tab_width = 2
