[profile.default]
src = 'src'
test = 'tests'
libs = ['lib']
out = 'out'
optimizer = true
solc_version = '0.8.20'
evm_version = 'london'

[rpc_endpoints]
optimism = "${OPTIMISTIC_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
optimism = { key = "${OPTIMISTIC_API_KEY}", url = "${OPTIMISTIC_API_URL}" }
polygon = { key = "${POLYSCAN_API_KEY}", url = "${POLYSCAN_API_URL}" }
base = { key = "${BASESCAN_API_KEY}", url = "${BASESCAN_API_URL}" }

[fmt]
tab_width = 2
line_length = 120
bracket_spacing = true
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
ignore = ["lib/**"]
